name: Setup Rust Cache
description: Setup Cargo registry cache and optionally sccache for Rust builds
inputs:
  cache-prefix:
    description: Prefix for the cache key
    required: false
    default: "cargo"
  extra-cache-paths:
    description: Additional paths to cache (newline separated)
    required: false
    default: ""
  with-sccache:
    description: Whether to install sccache
    required: false
    default: "true"
  sccache-scope:
    description: Scope name for sccache cache key (e.g. debug, release, clippy, py)
    required: false
    default: "default"
runs:
  using: composite
  steps:
    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ${{ inputs.extra-cache-paths }}
        key: ${{ inputs.cache-prefix }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ inputs.cache-prefix }}-${{ runner.os }}-${{ runner.arch }}-
    - name: Setup sccache environment
      if: inputs.with-sccache == 'true'
      shell: bash
      run: |
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "SCCACHE_IDLE_TIMEOUT=0" >> $GITHUB_ENV
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
        echo "SCCACHE_GHA_CACHE_KEY=sccache-${{ inputs.sccache-scope }}-${{ runner.os }}-${{ runner.arch }}" >> $GITHUB_ENV
    - name: Install sccache
      if: inputs.with-sccache == 'true'
      uses: mozilla-actions/sccache-action@v0.0.9
